const types = {
    SET_DOCUMENTS: 'SET_DOCUMENTS',
    SET_ACTIVE_USER: 'SET_ACTIVE_USER',
    SET_ACTIVE_DOCUMENT: 'SET_ACTIVE_DOCUMENT',
    UPDATE_DOCUMENTS_LIST: 'UPDATE_DOCUMENTS_LIST',
    FILTER_DOCUMENTS: 'FILTER_DOCUMENTS'
}

export default types;