const types = {
    SET_DOCUMENTS: 'SET_DOCUMENTS',
    SET_ACTIVE_USER: 'SET_ACTIVE_USER',
    SET_ACTIVE_DOCUMENT: 'SET_ACTIVE_DOCUMENT',
    UPDATE_DOCUMENTS_LIST: 'UPDATE_DOCUMENTS_LIST',
    RESET_ACTIVE_DOCUMENT: 'RESET_ACTIVE_DOCUMENT'
}

export default types;